import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';

export function ContentCopypaste() {
  const [copied, setCopied] = useState<string | null>(null);

  const content = {
    'bennett-brief-2026-04-09': {
      title: 'The Discipline Paradox: Why Motivation Fails But Systems Work',
      text: `The Discipline Paradox: Why Motivation Fails But Systems Work

You're not lazy. Your system is.

Most people think they're broken because they lack motivation. The problem isn't willpower. It's structure.

Here's what nobody talks about: Motivation is a lie. It's a feeling that comes and goes like the weather. You can't build anything sustainable on a feeling.

THE MOTIVATION MYTH

Day 1: You're fired up. You meditate. You work out. You crush your goals.

Day 14: You're tired. You didn't sleep well. Motivation is gone. So you skip the routine.

Day 30: You've quit entirely and convinced yourself "that system doesn't work."

What actually happened: You relied on motivation instead of systems.

Motivation is a bonus. When it shows up, great. When it doesn't, you shouldn't notice.

THE REAL GAME: SYSTEMS

A system is a set of rules that execute whether you feel like it or not.

Example 1: The Trading System
Most traders fail because they trade on emotion. They win. They feel invincible. They over-leverage.
They lose. They panic. They exit at the worst possible time.

A real system removes emotion:
- Fixed risk per trade (2% always)
- Pre-defined entries and exits
- Mechanical rules, no thinking
- Follow the system, not your gut

Result: 55% win rate that compounds for years beats 80% win rate that blows up the account.

Example 2: The Content System
Most creators fail because they post when they "feel inspired."

A real system says:
- Monday 9 AM: Post #1
- Wednesday 9 AM: Post #2
- Friday 9 AM: Post #3

You don't ask yourself if you feel like creating. The system says "create," so you create.

Result: 3 posts/week for 52 weeks = 156 posts. That's a brand.

WHY SYSTEMS BEAT WILLPOWER

Willpower is finite. You have a limited amount each day. Every decision drains it.

Should I work out today? Should I post? Should I write? Each "should" costs willpower.

Systems are automatic. Once built, they require zero willpower.

You don't think about brushing your teeth. It's automatic. You don't think about your system. You just execute it.

THE SETUP COST IS REAL

Building a system takes effort upfront.

Defining your trading rules? Painful. Takes hours of backtesting.
Setting up your content calendar? Takes time. Takes thinking.
Creating your morning routine? Boring. Feels useless for the first week.

But here's the payoff: Once the system is built, execution becomes automatic.

THE SYSTEMS I'VE BUILT THAT ACTUALLY WORK

Trading System (3 years active)
- Risk: 2% per trade (pre-defined)
- Entries: VWAP + EMA (mechanical)
- Exits: Profit targets or stops (pre-set)
- Emotion removed? Completely.
- Result: 55% win rate, +$50K accumulated

Content System (6 months active)
- Schedule: Mon/Wed/Fri 9 AM PT
- Format: 800-1,000 words
- Distribution: Substack, LinkedIn, Twitter, Reddit (auto-generated)
- Motivation required? Zero.
- Result: 287 subscribers, 38% open rate, 18.7K reach

Email System (Active)
- Rule: Reply within 2 hours
- Filter: Auto-flag sensitive topics
- Response: Generated by AI, humanized
- Decision-making required? Minimal.
- Result: 95% response rate, never miss important emails

THE REAL DISCIPLINE

Discipline isn't about pushing harder.

Discipline is building a system that doesn't require pushing.

The moment you're pushing, it's too hard. You're relying on willpower again.

Real discipline is boring. It's automatic. It's doing the thing because the system says to do the thing.

YOUR MOVE

Here's what I see: Most people are trying to win through willpower.

They're fighting every day. "Should I work out?" "Should I post?" "Should I trade?"

Every decision is a battle. By day 30, they're exhausted and quit.

The winners aren't smarter or more motivated. They just removed the decision.

They built a system that says: "We do this. We don't ask why. We just do it."

If you want to change your life in 90 days:

1. Identify one area that matters (trading, content, fitness, whatever)
2. Build the system (this takes 3-5 hours of focused work)
3. Execute the system (zero willpower required, just follow the rules)
4. Review after 90 days (then adjust based on data)

That's it. That's the game.

Motivation is a distraction. Systems are the move.

---

Bennett's Brief - Systems, Discipline, Execution`
    }
  };

  const handleCopy = (key: string) => {
    const item = content[key as keyof typeof content];
    if (item) {
      navigator.clipboard.writeText(item.text);
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 border border-blue-200">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Bennett's Brief</h2>
        <p className="text-gray-600 mb-6">Copy and paste ready content - no special characters</p>

        {Object.entries(content).map(([key, item]) => (
          <div key={key} className="bg-white rounded-lg border border-gray-200 p-4 mb-4">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">{item.title}</h3>
                <p className="text-sm text-gray-500 mt-1">Clean format, ready to paste</p>
              </div>
              <button
                onClick={() => handleCopy(key)}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition"
              >
                {copied === key ? (
                  <>
                    <Check size={18} />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy size={18} />
                    Copy to Clipboard
                  </>
                )}
              </button>
            </div>

            <div className="bg-gray-50 rounded border border-gray-200 p-4 max-h-96 overflow-y-auto font-mono text-sm text-gray-700 whitespace-pre-wrap">
              {item.text.substring(0, 500)}...
            </div>
            <p className="text-xs text-gray-500 mt-2">{item.text.length} characters</p>
          </div>
        ))}
      </div>
    </div>
  );
}
